version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  format:
    desc: Format all code
    deps:
      - format-backend
      - format-importer
      - format-frontend

  build:
    desc: Build the backend and importer programs
    deps:
      - build-backend
      - build-importer

  build-backend:
    desc: Build the backend Go program
    dir: backend
    cmds:
      - go build -o ../transit-ch-backend{{exeExt}} .

  build-importer:
    desc: Build the importer Go program
    dir: importer
    cmds:
      - go build -o ../transit-ch-importer{{exeExt}} .

  format-backend:
    desc: Format backend Go code
    dir: backend
    cmds:
      - go fix ./...
      - go fmt ./...

  format-importer:
    desc: Format importer Go code
    dir: importer
    cmds:
      - go fix ./...
      - go fmt ./...

  format-frontend:
    desc: Format frontend TypeScript code
    dir: frontend
    cmds:
      - npm run lint -- --fix
      - npm run format

  lint:
    desc: Run linters for all code
    cmds:
      - task lint-frontend
      - docker run --rm -v {{toSlash .ROOT_DIR}}/importer:/app -w /app golangci/golangci-lint:v2.13.1 golangci-lint run -v --timeout 5m
      - docker run --rm -v {{toSlash .ROOT_DIR}}/backend:/app -w /app golangci/golangci-lint:v2.13.1 golangci-lint run -v --timeout 5m

  lint-frontend:
    desc: Run linters for frontend TypeScript code
    dir: frontend
    cmds:
      - npm run lint

  test:
    desc: Run backend and importer tests
    deps:
      - test-backend
      - test-importer

  test-backend:
    desc: Run backend Go tests
    dir: backend
    cmds:
      - go test ./...

  test-importer:
    desc: Run importer Go tests
    dir: importer
    cmds:
      - go test ./...

  build-frontend:
    desc: Build the Angular frontend
    dir: frontend
    cmds:
      - npm run build
